<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Users extends CI_Controller
{

  public function __construct()
  {
    parent::__construct();
    //Do your magic here
    $this->MRef->logged();
    $this->MRef->sessionstart();
    $this->maintitle = "Users - " . $this->session->userdata('appname');
    $this->pageheading = "Users";
    $this->load->model('MUsers', 'm');
    $this->load->library('form_validation');
  }

  public function index()
  {
    $data = array(
      "title" => $this->maintitle,
      "pageheading" => $this->pageheading,
      "users_data" => $this->m->get_all()
    );
    $this->load->view('users/users', $data);
  }

  public function create()
  {
    $data = array(
      'button' => 'Create',
      'action' => site_url('users/create_action'),
      'auth_id' => set_value('auth_id'),
      'auth_name' => set_value('auth_name'),
      'auth_image' => set_value('auth_image'),
      'auth_user' => set_value('auth_user'),
      'auth_email' => set_value('auth_email'),
      'auth_pws' => set_value('auth_pws'),
      'auth_token' => set_value('auth_token'),
      'auth_create' => set_value('auth_create'),
      'auth_verify' => set_value('auth_verify'),
    );
    $this->load->view('users/manage', $data);
  }

  public function create_action()
  {
    $this->_rules();
    if ($this->form_validation->run() == FALSE) {
      $this->create();
    } else {
      $data = array(
        'auth_id' => $this->m->KodeUser(),
        'auth_name' => $this->input->post('auth_name', TRUE),
        'auth_image' => $this->input->post('auth_image', TRUE),
        'auth_access' => "ADMIN",
        'auth_user' => $this->input->post('auth_user', TRUE),
        'auth_email' => $this->input->post('auth_email', TRUE),
        'auth_pws' => $this->input->post('auth_pws', TRUE),
        'auth_create' => date('Y-m-d'),
      );

      $this->m->insert($data);
      $this->session->set_flashdata('message', 'Create Record Success');
      redirect(site_url('users'));
    }
  }

  public function verifychange($id)
  {
    $row = $this->m->get_by_id($id);
    $data = array(
      'auth_verify' => $row->auth_verify == "Y" ? "N" : "Y",
    );

    $this->m->update($id, $data);
    $this->session->set_flashdata('message', 'Update Record Success');
    redirect(site_url('users'));
  }

  public function delete($id)
  {
    $row = $this->m->get_by_id($id);
    if ($row) {
      $this->m->delete($id);
      $this->session->set_flashdata('message', 'Delete Record Success');
      redirect(site_url('users'));
    } else {
      $this->session->set_flashdata('message', 'Record Not Found');
      redirect(site_url('users'));
    }
  }

  public function _rules()
  {
    $this->form_validation->set_rules('auth_name', 'Name', 'trim|required');
    $this->form_validation->set_rules('auth_image', 'Image', 'trim');
    $this->form_validation->set_rules('auth_user', 'Username', 'trim|required');
    $this->form_validation->set_rules('auth_email', 'Email', 'trim|required');
    $this->form_validation->set_rules('auth_pws', 'Password', 'trim');

    $this->form_validation->set_rules('auth_id', 'auth_id', 'trim');
    $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }
}

/* End of file Users.php */
/* Location: ./application/controllers/Users.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-29 12:43:05 */
/* http://harviacode.com */
