<?php

if (!defined('BASEPATH'))
  exit('No direct script access allowed');

class MUsers extends CI_Model
{

  public $table = 'tb_auth';
  public $id = 'auth_id';
  public $order = 'DESC';

  function __construct()
  {
    parent::__construct();
  }

  // get all
  function get_all()
  {
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db->where($this->id, $id);
    return $this->db->get($this->table)->row();
  }

  // get total rows
  function total_rows($q = NULL)
  {
    $this->db->like('auth_id', $q);
    $this->db->or_like('auth_name', $q);
    $this->db->or_like('auth_image', $q);
    $this->db->or_like('auth_access', $q);
    $this->db->or_like('auth_user', $q);
    $this->db->or_like('auth_email', $q);
    $this->db->or_like('auth_pws', $q);
    $this->db->or_like('auth_token', $q);
    $this->db->or_like('auth_create', $q);
    $this->db->or_like('auth_verify', $q);
    $this->db->from($this->table);
    return $this->db->count_all_results();
  }

  // get data with limit and search
  function get_limit_data($limit, $start = 0, $q = NULL)
  {
    $this->db->order_by($this->id, $this->order);
    $this->db->like('auth_id', $q);
    $this->db->or_like('auth_name', $q);
    $this->db->or_like('auth_image', $q);
    $this->db->or_like('auth_access', $q);
    $this->db->or_like('auth_user', $q);
    $this->db->or_like('auth_email', $q);
    $this->db->or_like('auth_pws', $q);
    $this->db->or_like('auth_token', $q);
    $this->db->or_like('auth_create', $q);
    $this->db->or_like('auth_verify', $q);
    $this->db->limit($limit, $start);
    return $this->db->get($this->table)->result();
  }

  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db->where($this->id, $id);
    $this->db->update($this->table, $data);
  }

  // delete data
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }

  // generate kode user
  public function KodeUser()
  {
    $this->load->model('MRef', 'r');
    return $this->r->GenerateKode("US", $this->table, "auth_id");
  }
}

/* End of file MUsers.php */
/* Location: ./application/models/MUsers.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-29 12:43:05 */
/* http://harviacode.com */
